# Site settings
author: William Dewey
title: Adventures in Coding
header-img: img/home-bg.png
email: wkdewey@gmail.com
copyright_name: William Dewey
description: > # this means to ignore newlines until "baseurl:"
  Thoughts on programming, web development, and tech
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  wkdewey

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
